# 커버리지 보고만 작성하고 커버리지에 따라 차단 x
coverage:
  status:
    patch: off
    project: off

comment:
  layout: 'header, reach, diff, flags, components'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

component_management:
  individual_components:
    - component_id: web
      name: '@sbooky/web'
      paths:
        - apps/web/**
