packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # react
  'react': '^19.0.0'
  '@types/react': '^19.0.7'
  # react-dom
  'react-dom': '^19.0.0'
  '@types/react-dom': '^19.0.3'

  # tailwindcss
  'autoprefixer': '^10.4.20'
  'postcss': '^8.5.1'
  'tailwindcss': '^3.4.17'
  'class-variance-authority': '^0.7.1'
  'clsx': '^2.1.1'
  'tailwind-merge': '^3.0.1'

  # typescript
  'typescript': '^5.8.3'
  '@types/node': '^22.14.1'

  'zod': '^3.24.1'
  'react-hook-form': '^7.54.2'

  # next
  'next': '^15.3.0'
  '@next/eslint-plugin-next': '^15.3.0'
  '@next/third-parties': '^15.3.0'

  # react-query
  '@tanstack/react-query': '^5.66.5'
  '@tanstack/react-query-devtools': '^5.64.1'

  # motion
  'motion': '^12.7.0'
