export const ALL_GHOSTS = [
  'BAEKDO_CAT_GHOST',
  'BASIC_GHOST',
  'CAT_GHOST',
  'CHEESE_CAT_GHOST',
  'DETECTIVE_GHOST',
  'FRANKENSTEIN_GHOST',
  'LITTLEPRINCE_GHOST',
  'MUMMY_GHOST',
  'REDHOOD_GHOST',
  'SIAMESE_CAT_GHOST',
  'WIZARD_GHOST',
];
