name: Deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ['main']

jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
          node-version: 22
          # node-version-file: '.nvmrc'

      - name: Vercel CLI 설치
        run: pnpm install --global vercel@latest

      - name: Vercel 환경 변수 가져오기
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Project Artifacts 빌드하기
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Vercel에 Project Artifacts 배포하기
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
